### ISSUE TITLE
REACT: barebones food cards main viewing page

### ISSUE THREAD

**Issue by emmakoehmstedt** [emmakoehmstedt/healthy-games-for-healthy-people-and-healthy-planet#12]
**Refer to the Figma Protoype for this task.**

**General Description.**
There should be a left hand calculator and the main part of the page should be a list of food cards.

You can use dummy data to show the food cards. 

Minimal CSS needed for this task. 

**Requirements:**
- Top Bar (Header)
- Side Bar (Calculator)
- Main Part of Page (Food Cards - picture of food and name of food on each card) 
- The Food cards should be scrollable and the top bar / calculator should be in fixed position

**Dependencies**
- NextJS project created
- Home Screen Created with functioning button that leads to this current page

**Time Estimate**
- ~2 hours

**Number of People**
- 1

**Comment by garrettberliner** [comment]
Emma and Gerald worked on this & completed it 2/21
