### ISSUE TITLE
Test issue for Workplace Setup

### ISSUE THREAD

**Issue by garrettberliner** [emmakoehmstedt/healthy-games-for-healthy-people-and-healthy-planet#2]
This is an example issue to ensure this works for our 'Workplace Setup' assignment. We will use this to state the problems each of us are stuck on to try and get help from other team members.

**Comment by emmakoehmstedt** [comment]
This was before adding the Project Board. We won't be adding issues here directly.

**Comment by emmakoehmstedt** [comment]
issue closed
