### ISSUE TITLE
Add to Calculator Functionality (big task)

### ISSUE THREAD

**Issue by emmakoehmstedt** [emmakoehmstedt/healthy-games-for-healthy-people-and-healthy-planet#20]
Hook up add to calculator button to functionality (should show up in side bar)
Add functionality to clear calculator and the delete button for each item in the calculator

**Comment by garrettberliner** [comment]
Emma worked on Functionality 2/28 & Garrett worked on CSS on 2/29 - ready to merge changes for 3/1 team meeting
