### ISSUE TITLE
DATABASE: Add the fresh herbs to the database and the google/spreadsheet for "Fresh Herbs" -Basil, Chive, Oregano

### ISSUE THREAD

**Issue by ghendrix-git** [emmakoehmstedt/healthy-games-for-healthy-people-and-healthy-planet#22]
Add Fresh Herbs to database, -basil, chive, and oregano-

**Comment by garrettberliner** [comment]
Renamed the Fresh Herbs label to Basil, Chives, Oregano - Do I need to create individual rows?

**Comment by garrettberliner** [comment]
Need someone to review: Successfully modified tables in Supabase to reflect changes
